spring:
  datasource:
    url: jdbc:postgresql://infra.walkingcoders.xyz/javahack
    username: dbuser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog-master.xml


